name: ItemFrameClicker
main: me.Phil14052.ItemFrameClicker.ItemFrameClicker
version: 1.0
author: phil14052
description: Adds the ability to make clickable item frames
commands:
  ifc:
    description: itemframeclicker Plugin Main Command
    aliases: [itemframeclicker]